######################## default configuration ####################
baseURL = "https://examplesite.com"
languageCode = "en-us"
title = "Project RED"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Team"
  URL = "team"
  weight = 2
  
  [[menu.main]]
  name = "News"
  URL = "blog"
  weight = 3
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 4

  [[menu.main]]
  name = "Donate"
  URL = "https://www.gofundme.com/f/respiratory-emergency-device-red-ventilator"
  weight = 5

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.footer]]
  name = "Team"
  URL = "team"
  weight = 2
  
  [[menu.footer]]
  name = "News"
  URL = "blog"
  weight = 3
  
  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 4

  [[menu.footer]]
  name = "Donate"
  URL = "https://www.gofundme.com/f/respiratory-emergency-device-red-ventilator"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "Project RED - A low-cost Ventilator project"
author = "Captain Cook"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = "0124857985320"
email = "demo@email.com"
location = "Sunnyvale, California"
# copyright
copyright = "| Project RED |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = false

############################ news letter ########################
#[params.newsletter]
#enable = false
#title = "Join Our Newsletter"
#content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"

############################# social site ########################
#[[params.social]]
#title = "facebook"
#icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#title = "twitter"
#icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#title = "instagram"
#icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#title = "github"
#icon = "ti-github" # themify icon : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#title = "linkedin"
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
#link = "#"